### ISSUE TITLE
odin crashes when opened

### ISSUE THREAD

**Issue by sabotagebeats** [odinblockchain/Odin#11]
This issue tracker is only for technical issues related to ODIN Core.
General ODIN questions and/or support requests and are best directed to the [ODIN Discord](https://discord.gg/Wu2Cs3w).

### Describe the issue
from log: 

EXCEPTION: St13runtime_error        ListMintedCoins : cannot create DB cursor        C:\Users\user\Downloads\odin-1.4.2-win64\odin-1.4.2\bin\odin-qt.exe in Runaway exception         2018-10-26 23:16:42 CDBEnv::EnvShutdown : Error -30974 shutting down database environment: DB_RUNRECOVERY: Fatal error, run database recovery

#### If so, please list the steps to reproduce below:
1. open odin
2. see error
3. odin closes

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of ODIN Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: windows 10 64 bit
- CPU: i5
- RAM: 32
- Disk size: 3/4 tb
- Disk Type (HD/SDD): hd

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

EXCEPTION: St13runtime_error        ListMintedCoins : cannot create DB cursor        C:\Users\user\Downloads\odin-1.4.2-win64\odin-1.4.2\bin\odin-qt.exe in Runaway exception         2018-10-26 23:16:42 CDBEnv::EnvShutdown : Error -30974 shutting down database environment: DB_RUNRECOVERY: Fatal error, run database recovery

**Comment by sabotagebeats** [comment]
deleted all files except .conf and wallet.dat and I was able to get the wallet to boot up again. currently synchronizing

**Comment by sabotagebeats** [comment]
crashing again, same error.

**Comment by sabotagebeats** [comment]
this is an excerpt from the db text file 

`PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
file wallet.dat has LSN 1/253783, past end of log at 1/1103
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
file wallet.dat has LSN 1/253783, past end of log at 1/1103
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
file wallet.dat has LSN 1/253895, past end of log at 1/1103
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
file wallet.dat has LSN 1/253783, past end of log at 1/1103
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
file wallet.dat has LSN 1/5285, past end of log at 1/1103
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
file wallet.dat has LSN 1/253783, past end of log at 1/1103
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
file wallet.dat has LSN 1/5285, past end of log at 1/1103
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
file wallet.dat has LSN 1/253783, past end of log at 1/1103
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
DB_ENV->log_flush: LSN of 1/5285 past current end-of-log of 1/1664
Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
PANIC: DB_RUNRECOVERY: Fatal error, run database recovery
wallet.dat: unable to flush page: 4
DB_ENV->log_flush: LSN of 1/253783 past current end-of-log of 1/1664
Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
PANIC: DB_RUNRECOVERY: Fatal error, run database recovery
wallet.dat: unable to flush page: 83
PANIC: fatal region error detected; run recovery
wallet.dat: write failed for page 86
wallet.dat: unable to flush page: 86
DB_ENV->log_flush: LSN of 1/253895 past current end-of-log of 1/1664
Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
PANIC: DB_RUNRECOVERY: Fatal error, run database recovery
wallet.dat: unable to flush page: 87
txn_checkpoint: failed to flush the buffer cache: DB_RUNRECOVERY: Fatal error, run database recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
File handles still open at environment close
Open file handle: E:\odinblockchain\wallet.dat
Open file handle: E:\odinblockchain\database\log.0000000001
PANIC: fatal region error detected; run recovery
`

**Comment by sabotagebeats** [comment]
i deleted the following files and folders to get it up and running again without having to reload the blockchain:

backups
database
sporks
zerocoin
.lock
db
debug

**Comment by sabotagebeats** [comment]
issue keeps returning

**Comment by sabotagebeats** [comment]
since i'm still having the issue and i'm unable to run the wallet in a stable manner i'm trying to troubleshoot this. I've removed all the files except masternode.conf, and wallet.dat. this allows me to boot odin without crashing. Now i've run the "wallet tools - salvage wallet, and it's created a wallet.bak file. Now my tx's don't appear anymore and it is re-synching the network. Hopefully when the network synchs, the tx's will appear and everything will be good. If so then I'm guessing it was a corrupt wallet.dat, if not then we have bigger problems still.

**Comment by 7h3v01c3** [comment]
Ok is your machine going to sleep? Or do you have an Antivirus running

**Comment by sabotagebeats** [comment]
it looks like wallet tools - salvage wallet has worked for now. I haven't had any problems since. I will reopen this if I have more problems.
