### ISSUE TITLE
Feature: Dark Theme

### ISSUE THREAD

**Issue by Manbearpixel** [odinblockchain/Odin#12]
## Feature Suggestion:
Implement a dark theme for the ODIN GUI Wallet.

## Why?
While the default light theme is very nice it can become bothersome at night for the eyes. Additionally, a new theme would demonstrate how others can offer other theme tweaks in the future.

**Comment by Manbearpixel** [comment]
+1

**Comment by lancehall123** [comment]
How long is this going to take? Estimated.

**Comment by Manbearpixel** [comment]
Initial support will be included in the next release. Closing.
